server:
  port: 8800
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://containers-us-west-175.railway.app:6910/railway
    username: root
    password: RzBASQopHkll3R4yOHdY
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-4
  redis:
    host: containers-us-west-68.railway.app
    port: 7386
    database: 0
    timeout: 1800000
    password: wGKi13BS6JDhLWXLZuQA
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲